### PR TITLE
Add russian language

### PR DESCRIPTION
**Pull request by iZerus**
Please also add the ability to translate the following UI elements:
[screen 1](https://disk.yandex.ru/i/yOpxY7tJw7O_Kw)
[screen 2](https://disk.yandex.ru/i/UsIqmY-TEMhuTQ)

### CODE REVIEW

**Comment by MadaraUchiha** [comment]
Thank you for the contribution! I'll look into what I need to do to localize those two scenarios.

Want me to wait with merging this until those two can be localized as well?

**Comment by iZerus** [comment]
> Thank you for the contribution! I'll look into what I need to do to localize those two scenarios.
> 
> Want me to wait with merging this until those two can be localized as well?

Yes, as soon as it is ready, write to me here, I will translate)

**Comment by MadaraUchiha** [comment]
I've handled the localization of the quadrum names, you should pull and rebase/merge `master` into your branch to see it.

As for the window description, you do that with the DefInjected directory

See the directory structure instructions here https://rimworldwiki.com/wiki/Modding_Tutorials/Mod_folder_structure#The_Languages_folder (basically, create a `DefInjected` directory next to the Keyed directory, and add a `MainButtonDef` directory inside that, then a `MainButtons.xml` file inside.

Here's an example from how the main game buttons are translated https://github.com/Ludeon/RimWorld-ru/blob/master/Core/DefInjected/MainButtonDef/MainButtons.xml, the names of the elements in the XML should match the ones here https://github.com/MadaraUchiha/Reminders/blob/master/Defs/MainButtons.xml (eg. `<Reminders.description>TEXT</Reminders.description>`)

**Comment by iZerus** [comment]
I added it, but I'm not sure what is correct.

**Comment by MadaraUchiha** [comment]
It's not correct, take a look at the example https://github.com/Ludeon/RimWorld-ru/blob/master/Core/DefInjected/MainButtonDef/MainButtons.xml

**Comment by iZerus** [comment]
It should work)

**Review by MadaraUchiha — APPROVED** [review]

**Pull request merged**
